---
name: Terraform Apply

description: Terraform Apply

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true
  VERCEL_API_TOKEN:
    description: Vercel の API トークン
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ inputs.working-directory }}
      env:
        TF_VAR_vercel_api_token: ${{ inputs.VERCEL_API_TOKEN }}
      shell: bash
