---
name: Labeler

on:
  pull_request:

jobs:
  auto-labeling:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
